name: Run Tests

on: [push]

jobs:
  test_p3:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Get cmake
      uses: threeal/cmake-action@v1.3.0
    - name: build application
      run: |
        cmake -B build
        make -C build
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: 3.11
    - name: Run tests
      uses: dariocurr/pytest-summary@main
      with:
       paths: test/test_praxis3.py
       options: --quiet
       show: all
